# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestInternetdezactivare():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_internetdezactivare(self):
    self.driver.get("https://www.orange.ro/accounts/login-user?ak=4a8bdd2da816486f9748e014749d0fccIR46I279L4exhWsn20XVjHXDe&ud=1")
    self.driver.set_window_size(1536, 824)
    self.driver.find_element(By.ID, "login").click()
    self.driver.find_element(By.ID, "login").send_keys("predut1978@gmail.com")
    self.driver.find_element(By.ID, "password").send_keys("preSuiram1!")
    self.driver.find_element(By.ID, "password").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, "body").click()
    self.driver.find_element(By.CSS_SELECTOR, "#serviceInfo_1 .even:nth-child(2) .deactivate").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "#serviceInfo_1 .even:nth-child(2) .deactivate")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.ID, "faceboxConfirm").click()
    self.driver.find_element(By.CSS_SELECTOR, "#serviceInfo_1 .odd:nth-child(5) .deactivate").click()
    self.driver.find_element(By.ID, "faceboxConfirm").click()
    self.driver.find_element(By.ID, "faceboxConfirm").click()
  
